import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import { getSession, signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import AuthNav from "../components/AuthNav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Link Things</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-neutral-300">
        <Header />
        <div className="container border">
          <div className="my-2"></div>
          Home
        </div>
      </main>
    </>
  );
};

export default Home;

import type { GetServerSidePropsContext } from "next";
export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const session = await getSession(ctx);
  if (session) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
}
