import type { IconType } from "react-icons";
import {
  IoLogoTwitter,
  IoBagHandle,
  IoCameraSharp,
  IoCardSharp,
  IoCartSharp,
  IoChatbox,
  IoCodeSlashSharp,
  IoGameController,
  IoHeadsetSharp,
  IoLogoFacebook,
  IoLogoFigma,
  IoLogoGithub,
  IoLogoGitlab,
  IoLogoGoogle,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoLogoPaypal,
  IoLogoReddit,
  IoLogoSnapchat,
  IoLogoTiktok,
  IoLogoTumblr,
  IoLogoTwitch,
  IoLogoUsd,
  IoLogoVenmo,
  IoLogoVimeo,
  IoLogoWechat,
  IoLogoWhatsapp,
  IoLogoYoutube,
  IoMusicalNotesSharp,
  IoStorefrontSharp,
  IoVideocamSharp,
  IoWalkSharp,
  IoWalletSharp,
} from "react-icons/io5";

export const IconsImages = [
  { icon: IoLogoTwitter, name: "twitter" },
  { icon: IoBagHandle, name: "shop" },
  { icon: IoCameraSharp, name: "camera" },
  { icon: IoCardSharp, name: "card" },
  { icon: IoCartSharp, name: "cart" },
  { icon: IoChatbox, name: "chat" },
  { icon: IoCodeSlashSharp, name: "code" },
  { icon: IoGameController, name: "game" },
  { icon: IoHeadsetSharp, name: "audio" },
  { icon: IoLogoFacebook, name: "facebook" },
  { icon: IoLogoFigma, name: "figma" },
  { icon: IoLogoGithub, name: "github" },
  { icon: IoLogoGitlab, name: "gitlab" },
  { icon: IoLogoGoogle, name: "google" },
  { icon: IoLogoInstagram, name: "instagram" },
  { icon: IoLogoLinkedin, name: "linkedin" },
  { icon: IoLogoPaypal, name: "paypal" },
  { icon: IoLogoReddit, name: "reddit" },
  { icon: IoLogoSnapchat, name: "snapchat" },
  { icon: IoLogoTiktok, name: "tiktok" },
  { icon: IoLogoTumblr, name: "tumblr" },
  { icon: IoLogoTwitch, name: "twitch" },
  { icon: IoLogoUsd, name: "money" },
  { icon: IoLogoVenmo, name: "venmo" },
  { icon: IoLogoVimeo, name: "vimeo" },
  { icon: IoLogoWechat, name: "wechat" },
  { icon: IoLogoWhatsapp, name: "whatsapp" },
  { icon: IoLogoYoutube, name: "youtube" },
  { icon: IoMusicalNotesSharp, name: "music" },
  { icon: IoStorefrontSharp, name: "store" },
  { icon: IoVideocamSharp, name: "video" },
  { icon: IoWalkSharp, name: "user" },
  { icon: IoWalletSharp, name: "wallet" },
];

const Icons = {
  twitter: IoLogoTwitter,
  shop: IoBagHandle,
  camera: IoCameraSharp,
  card: IoCardSharp,
  cart: IoCartSharp,
  chat: IoChatbox,
  code: IoCodeSlashSharp,
  game: IoGameController,
  audio: IoHeadsetSharp,
  facebook: IoLogoFacebook,
  figma: IoLogoFigma,
  github: IoLogoGithub,
  gitlab: IoLogoGitlab,
  google: IoLogoGoogle,
  instagram: IoLogoInstagram,
  linkedin: IoLogoLinkedin,
  paypal: IoLogoPaypal,
  reddit: IoLogoReddit,
  snapchat: IoLogoSnapchat,
  tiktok: IoLogoTiktok,
  tumblr: IoLogoTumblr,
  twitch: IoLogoTwitch,
  money: IoLogoUsd,
  venmo: IoLogoVenmo,
  vimeo: IoLogoVimeo,
  wechat: IoLogoWechat,
  whatsapp: IoLogoWhatsapp,
  youtube: IoLogoYoutube,
  music: IoMusicalNotesSharp,
  store: IoStorefrontSharp,
  video: IoVideocamSharp,
  user: IoWalkSharp,
  wallet: IoWalletSharp,
} as const

type IconKeys = keyof typeof Icons;

export const getIconByKey = (key: IconKeys): IconType | null => {
  const IconComponent = Icons[key];
  return IconComponent;
};

